/*
Section A --> Know your data                                  Time: 45 min
1.	Read the data from all tables.
2.	Find the country wise count of customers.
3.	Display the products which are not discontinued.
4.	Display the list of companies along with the product name that they are supplying.
5.	Display customer's information who stays in 'Mexico'
6.	Display the costliest item that is ordered by the customer.
7.	Display supplier id who owns highest number of products.
8.	Display month wise and year wise count of the orders placed.
9.	Which country has maximum suppliers.
10.	Which customers did not place any order.
*/
-- 1.	Read the data from all tables.
select * from customer;
select * from Orders;
select * from Supplier;
select * from Product;
select * from OrderItem;

-- 2.	Find the country wise count of customers.
select id,firstname,lastname,city,country,count(id) from customer group by country;

-- 3.	Display the products which are not discontinued.
select id,productname,IsDiscontinued from product where IsDiscontinued=0;

-- 4.	Display the list of companies along with the product name that they are supplying.
select s.id,s.companyname,p.id,p.productname 
from supplier s
join product p
on s.id = p.SupplierId;

-- 5.	Display customer's information who stays in 'Mexico'
select * from customer where country='mexico';

-- 6.	Display the costliest item that is ordered by the customer.
select a.Id, a.FirstName, a.LastName, a.City, a.Country, a.Phone, b.TotalAmount 
from customer a left join orders b on a.Id = b.CustomerId order by b.TotalAmount desc limit 1;

-- 7.	Display supplier id who owns highest number of products.
select supplierid,max(package) from product group by SupplierId having max(Package);

-- 8.	Display month wise and year wise count of the orders placed.
select month(orderdate),year(orderdate),count(ordernumber) from orders group by month(orderdate),year(orderdate);

-- 9.	Which country has maximum suppliers.
# 1st approach
select country,count(id) from supplier group by country order by count(id) desc limit 1;
# 2nd approach
select country,count(id) as supplier_count from supplier group by country 
having count(id) = (select max(supplier_count) from (select country,count(id) as supplier_count from supplier group by country)a );

-- 10.	Which customers did not place any order.
select * from customer o
where not exists (select * from orders i where o.id=i.CustomerId);

/*
Section B --> Know the business 			Time: 60 min.

1.	Arrange the product id, product name based on high demand by the customer.
2.	Display the number of orders delivered every year.
3.	Calculate year-wise total revenue.
4.	Display the customer details whose order amount is maximum including his past orders.
5.	Display total amount ordered by each customer from high to low.
A sales and marketing department of this company wants to find out how frequently customer have business with them. This can be done in two ways. (Answer Q 6 and Q 7 for the same)
6.	Approach 1. List the current and previous order amount for each customers.
7.	Approach 2. List the current and previous order amount for each customers.
8.	Find out top 3 suppliers in terms of revenue generated by their products.
9.	Display latest order date (should not be same as first order date) of all the customers with customer details.
10.	Display the product name and supplier name for each order
*/
select * from customer;
select * from Orders;
select * from Supplier;
select * from Product;
select * from OrderItem;

-- 1.	Arrange the product id, product name based on high demand by the customer.
# 1st apporach:
select o.productid,p.productname,sum(quantity) 
from orderitem o
join product p 
on o.ProductId = p.id
group by ProductId
order by sum(Quantity) desc;


-- 2.	Display the number of orders delivered every year.
select year(orderdate),count(id) from orders group by year(orderdate);

-- 3.	Calculate year-wise total revenue.
select year(orderdate),sum(totalamount) from orders group by year(orderdate);

-- 4.	Display the customer details whose order amount is maximum including his past orders.
select * from customer where id = (select CustomerId from 
(select CustomerId,sum(TotalAmount) from orders group by customerid order by sum(totalamount) desc limit 1) a);

-- 5.	Display total amount ordered by each customer from high to low.
select totalamount,customerid from orders group by customerid order by totalamount desc;


/* A sales and marketing department of this company wants to find out how frequently 
customer have business with them. This can be done in two ways. (Answer Q 6 and Q 7 for the same) */
-- 6 Approach 1. List the current and previous order amount for each customers.
select customerid,totalamount,
lag(totalamount) over (partition by CustomerId) 
from orders;

/* 7. Approach 2. Display the customerid, order ids and the 
order dates along with the previous order date and the next order date for every customer in the table:: */
select customerid, id, orderdate,
lag(orderdate) over (partition by customerid order by orderdate) as previous_order_date,
lead(orderdate) over (partition by customerid order by orderdate) as next_order_date
from orders;


-- 8.	Find out top 3 suppliers in terms of revenue generated by their products.
  select s.companyname,o.ProductId,sum(o.unitprice*o.quantity)
  from orderitem o
  join product p
  on o.ProductId = p.id
  join supplier s
  on s.id = p.SupplierId
  group by o.ProductId 
  order by sum(o.unitprice*o.quantity) desc limit 3;













